# Generated by Django 5.0.2 on 2024-02-17 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_name', models.CharField(help_text='Введите название лота', max_length=200, verbose_name='Название лота')),
                ('start_price', models.FloatField(help_text='Введите начальную цену в долларах', verbose_name='Начальная цена')),
                ('seller_link', models.CharField(help_text='Надо изменить тип данных', max_length=200, verbose_name='Телеграмм ник')),
                ('lot_geo', models.CharField(help_text='Введите геолокацию лота', max_length=200, verbose_name='Адрес')),
                ('lot_description', models.TextField(help_text='добавьте описание к лоту', verbose_name='Описание')),
            ],
        ),
    ]
