# Generated by Django 5.0.2 on 2024-02-18 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotlist', '0003_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
