# Generated by Django 5.0.2 on 2024-02-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotlist', '0004_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Новость картинка'),
        ),
    ]
