# Generated by Django 5.0.2 on 2024-02-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotlist', '0005_lot_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение лота')),
            ],
        ),
        migrations.RemoveField(
            model_name='lot',
            name='img',
        ),
        migrations.AddField(
            model_name='lot',
            name='img',
            field=models.ManyToManyField(to='lotlist.image'),
        ),
    ]
