# Generated by Django 5.0.2 on 2024-02-19 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotlist', '0008_readyornot_alter_lot_seller_link_lot_ready_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lot',
            name='ready_status',
        ),
        migrations.DeleteModel(
            name='ReadyOrNot',
        ),
    ]
