# Generated by Django 5.0.2 on 2024-02-19 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotlist', '0009_remove_lot_ready_status_delete_readyornot'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadyOrNot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(max_length=20, verbose_name='Статус лота')),
            ],
        ),
        migrations.AddField(
            model_name='lot',
            name='ready_status',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='lotlist.readyornot'),
        ),
    ]
