# Generated by Django 5.0.2 on 2024-02-23 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotlist', '0010_readyornot_lot_ready_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='start_time',
            field=models.DateTimeField(help_text='Укажите время начала аукциона', null=True, verbose_name='Время начала аукциона'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='lot_description',
            field=models.TextField(help_text='Добавьте описание к лоту', verbose_name='Описание'),
        ),
    ]
