# Generated by Django 5.0.2 on 2024-02-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotlist', '0011_lot_start_time_alter_lot_lot_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='start_time',
            field=models.DateTimeField(blank=True, help_text='Укажите время начала аукциона', null=True, verbose_name='Время начала аукциона'),
        ),
    ]
