# Generated by Django 5.0.2 on 2024-02-24 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotlist', '0013_lot_end_time_alter_lot_ready_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='end_time',
            field=models.DateTimeField(blank=True, help_text='Укажите время окончания аукциона', null=True, verbose_name='Время окончания аукциона'),
        ),
    ]
