# Generated by Django 5.0.2 on 2024-02-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotlist', '0016_rename_userprofile_userfinance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_username', models.CharField(max_length=100, verbose_name='Ник зарепорченого')),
                ('user_that_reported', models.CharField(max_length=100, verbose_name='Ник человека, который зарепортил')),
                ('cause', models.TextField(verbose_name='Причина')),
            ],
        ),
    ]
