# Generated by Django 5.0.2 on 2024-02-24 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotlist', '0017_reports'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reports',
            new_name='Report',
        ),
    ]
