# Generated by Django 5.0.2 on 2024-02-24 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotlist', '0018_rename_reports_report'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sell_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.CharField(max_length=100, verbose_name='Покупатель')),
                ('price', models.FloatField(verbose_name='Цена продажи')),
                ('sell_date', models.DateField(blank=True, null=True, verbose_name='Время продажи')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Продавеч')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotlist.lot', verbose_name='Лот')),
            ],
        ),
    ]
