# Generated by Django 5.0.2 on 2024-02-24 15:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotlist', '0019_sell_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sell_History',
            new_name='SellHistory',
        ),
    ]
